[theme]
base = "light"  # светлая базовая тема

# Основной акцент (темно-бежевый)
primaryColor = "#C47451"

# Фон приложения (пергаментный)
backgroundColor = "#F5F0E6"

# Фон для интерактивных виджетов (светло-бежевый)
secondaryBackgroundColor = "#EDE6D5"

# Цвет основного текста (тёмно-серый, близкий к коричневому) 
textColor = "#3C2F2F"

# Цвет ссылок
linkColor = "#A67B5B"

# Фон для блоков кода (светлый пергамент)
codeBackgroundColor = "#F4F1EC"

# Основной шрифт sans-serif
font = "Arial"

# Шрифт для кода
codeFont = "monospace"

# Шрифт для заголовков (если не задан, используется font) serif
headingFont = "Arial"

# Радиус скругления элементов – используем умеренное значение
baseRadius = "0.5rem"

# Цвет границ
borderColor = "#D4BFAA"

# Отображать границы вокруг виджетов ввода
showWidgetBorder = true

# Базовый размер шрифта (в пикселях)
baseFontSize = 16

# Отображать вертикальный разделитель между сайдбаром и основным контентом
showSidebarBorder = true