[theme]
base = "light"  # светлая базовая тема

# Основной акцент
primaryColor = "#C47451"

# Фон приложения 
backgroundColor = "#F5F0E6"

# Фон для интерактивных виджетов 
secondaryBackgroundColor = "#EDE6D5"

# Цвет основного текста 
textColor = "#3C2F2F"

# Цвет ссылок
linkColor = "#A67B5B"

# Фон для блоков кода
codeBackgroundColor = "#F4F1EC"

# Основной шрифт 
font = "Arial"

# Шрифт для кода
codeFont = "monospace"

# Шрифт для заголовков 
headingFont = "Arial"

# Радиус скругления элементов
baseRadius = "0.5rem"

# Цвет границ
borderColor = "#D4BFAA"

# Отображать границы вокруг виджетов ввода
showWidgetBorder = true

# Базовый размер шрифта (в пикселях)
baseFontSize = 16

# Отображать вертикальный разделитель между сайдбаром и основным контентом
showSidebarBorder = true
